import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { UiProvider } from "@/Providers/UiProvider";
import TanstackQueryProvider from "@/Providers/TanstackQueryProvider";
import AuthContextProviders from "@/Context/AuthContextProviders";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata = {
  title: "Task manager",
  description: "Generated by Reshma khanam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthContextProviders>
          <TanstackQueryProvider>
            <UiProvider>
              <div className="flex md:flex-row flex-col gap-10 overflow-hidden">
                <Header />
                <main className="flex-1">{children}</main>
              </div>
            </UiProvider>
          </TanstackQueryProvider>
        </AuthContextProviders>
      </body>
    </html>
  );
}
